/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRiwayatRouteImport } from './routes/_authenticated/riwayat'
import { Route as AuthenticatedProdukRouteImport } from './routes/_authenticated/produk'
import { Route as AuthenticatedPoRouteImport } from './routes/_authenticated/po'
import { Route as AuthenticatedPengaturanRouteImport } from './routes/_authenticated/pengaturan'
import { Route as AuthenticatedPelangganRouteImport } from './routes/_authenticated/pelanggan'
import { Route as AuthenticatedLanggananRouteImport } from './routes/_authenticated/langganan'
import { Route as AuthenticatedKeuntunganRouteImport } from './routes/_authenticated/keuntungan'
import { Route as AuthenticatedKasirRouteImport } from './routes/_authenticated/kasir'
import { Route as AuthenticatedCekKoneksiRouteImport } from './routes/_authenticated/cek-koneksi'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicMidtransWebhookRouteImport } from './routes/api/public/midtrans-webhook'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRiwayatRoute = AuthenticatedRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdukRoute = AuthenticatedProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoRoute = AuthenticatedPoRouteImport.update({
  id: '/po',
  path: '/po',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengaturanRoute = AuthenticatedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPelangganRoute = AuthenticatedPelangganRouteImport.update({
  id: '/pelanggan',
  path: '/pelanggan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLanggananRoute = AuthenticatedLanggananRouteImport.update({
  id: '/langganan',
  path: '/langganan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeuntunganRoute = AuthenticatedKeuntunganRouteImport.update({
  id: '/keuntungan',
  path: '/keuntungan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKasirRoute = AuthenticatedKasirRouteImport.update({
  id: '/kasir',
  path: '/kasir',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCekKoneksiRoute = AuthenticatedCekKoneksiRouteImport.update({
  id: '/cek-koneksi',
  path: '/cek-koneksi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMidtransWebhookRoute =
  ApiPublicMidtransWebhookRouteImport.update({
    id: '/api/public/midtrans-webhook',
    path: '/api/public/midtrans-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cek-koneksi': typeof AuthenticatedCekKoneksiRoute
  '/kasir': typeof AuthenticatedKasirRoute
  '/keuntungan': typeof AuthenticatedKeuntunganRoute
  '/langganan': typeof AuthenticatedLanggananRoute
  '/pelanggan': typeof AuthenticatedPelangganRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/po': typeof AuthenticatedPoRoute
  '/produk': typeof AuthenticatedProdukRoute
  '/riwayat': typeof AuthenticatedRiwayatRoute
  '/api/public/midtrans-webhook': typeof ApiPublicMidtransWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cek-koneksi': typeof AuthenticatedCekKoneksiRoute
  '/kasir': typeof AuthenticatedKasirRoute
  '/keuntungan': typeof AuthenticatedKeuntunganRoute
  '/langganan': typeof AuthenticatedLanggananRoute
  '/pelanggan': typeof AuthenticatedPelangganRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/po': typeof AuthenticatedPoRoute
  '/produk': typeof AuthenticatedProdukRoute
  '/riwayat': typeof AuthenticatedRiwayatRoute
  '/api/public/midtrans-webhook': typeof ApiPublicMidtransWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/cek-koneksi': typeof AuthenticatedCekKoneksiRoute
  '/_authenticated/kasir': typeof AuthenticatedKasirRoute
  '/_authenticated/keuntungan': typeof AuthenticatedKeuntunganRoute
  '/_authenticated/langganan': typeof AuthenticatedLanggananRoute
  '/_authenticated/pelanggan': typeof AuthenticatedPelangganRoute
  '/_authenticated/pengaturan': typeof AuthenticatedPengaturanRoute
  '/_authenticated/po': typeof AuthenticatedPoRoute
  '/_authenticated/produk': typeof AuthenticatedProdukRoute
  '/_authenticated/riwayat': typeof AuthenticatedRiwayatRoute
  '/api/public/midtrans-webhook': typeof ApiPublicMidtransWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/cek-koneksi'
    | '/kasir'
    | '/keuntungan'
    | '/langganan'
    | '/pelanggan'
    | '/pengaturan'
    | '/po'
    | '/produk'
    | '/riwayat'
    | '/api/public/midtrans-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/cek-koneksi'
    | '/kasir'
    | '/keuntungan'
    | '/langganan'
    | '/pelanggan'
    | '/pengaturan'
    | '/po'
    | '/produk'
    | '/riwayat'
    | '/api/public/midtrans-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/cek-koneksi'
    | '/_authenticated/kasir'
    | '/_authenticated/keuntungan'
    | '/_authenticated/langganan'
    | '/_authenticated/pelanggan'
    | '/_authenticated/pengaturan'
    | '/_authenticated/po'
    | '/_authenticated/produk'
    | '/_authenticated/riwayat'
    | '/api/public/midtrans-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicMidtransWebhookRoute: typeof ApiPublicMidtransWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/riwayat': {
      id: '/_authenticated/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof AuthenticatedRiwayatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produk': {
      id: '/_authenticated/produk'
      path: '/produk'
      fullPath: '/produk'
      preLoaderRoute: typeof AuthenticatedProdukRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/po': {
      id: '/_authenticated/po'
      path: '/po'
      fullPath: '/po'
      preLoaderRoute: typeof AuthenticatedPoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan': {
      id: '/_authenticated/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthenticatedPengaturanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pelanggan': {
      id: '/_authenticated/pelanggan'
      path: '/pelanggan'
      fullPath: '/pelanggan'
      preLoaderRoute: typeof AuthenticatedPelangganRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/langganan': {
      id: '/_authenticated/langganan'
      path: '/langganan'
      fullPath: '/langganan'
      preLoaderRoute: typeof AuthenticatedLanggananRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keuntungan': {
      id: '/_authenticated/keuntungan'
      path: '/keuntungan'
      fullPath: '/keuntungan'
      preLoaderRoute: typeof AuthenticatedKeuntunganRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kasir': {
      id: '/_authenticated/kasir'
      path: '/kasir'
      fullPath: '/kasir'
      preLoaderRoute: typeof AuthenticatedKasirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cek-koneksi': {
      id: '/_authenticated/cek-koneksi'
      path: '/cek-koneksi'
      fullPath: '/cek-koneksi'
      preLoaderRoute: typeof AuthenticatedCekKoneksiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/midtrans-webhook': {
      id: '/api/public/midtrans-webhook'
      path: '/api/public/midtrans-webhook'
      fullPath: '/api/public/midtrans-webhook'
      preLoaderRoute: typeof ApiPublicMidtransWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCekKoneksiRoute: typeof AuthenticatedCekKoneksiRoute
  AuthenticatedKasirRoute: typeof AuthenticatedKasirRoute
  AuthenticatedKeuntunganRoute: typeof AuthenticatedKeuntunganRoute
  AuthenticatedLanggananRoute: typeof AuthenticatedLanggananRoute
  AuthenticatedPelangganRoute: typeof AuthenticatedPelangganRoute
  AuthenticatedPengaturanRoute: typeof AuthenticatedPengaturanRoute
  AuthenticatedPoRoute: typeof AuthenticatedPoRoute
  AuthenticatedProdukRoute: typeof AuthenticatedProdukRoute
  AuthenticatedRiwayatRoute: typeof AuthenticatedRiwayatRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCekKoneksiRoute: AuthenticatedCekKoneksiRoute,
  AuthenticatedKasirRoute: AuthenticatedKasirRoute,
  AuthenticatedKeuntunganRoute: AuthenticatedKeuntunganRoute,
  AuthenticatedLanggananRoute: AuthenticatedLanggananRoute,
  AuthenticatedPelangganRoute: AuthenticatedPelangganRoute,
  AuthenticatedPengaturanRoute: AuthenticatedPengaturanRoute,
  AuthenticatedPoRoute: AuthenticatedPoRoute,
  AuthenticatedProdukRoute: AuthenticatedProdukRoute,
  AuthenticatedRiwayatRoute: AuthenticatedRiwayatRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicMidtransWebhookRoute: ApiPublicMidtransWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
