/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowcaseSlugRouteImport } from './routes/showcase.$slug'
import { Route as AuthenticatedStokLogRouteImport } from './routes/_authenticated/stok-log'
import { Route as AuthenticatedShiftRouteImport } from './routes/_authenticated/shift'
import { Route as AuthenticatedRiwayatRouteImport } from './routes/_authenticated/riwayat'
import { Route as AuthenticatedPromoRouteImport } from './routes/_authenticated/promo'
import { Route as AuthenticatedProdukRouteImport } from './routes/_authenticated/produk'
import { Route as AuthenticatedPoRouteImport } from './routes/_authenticated/po'
import { Route as AuthenticatedPengaturanRouteImport } from './routes/_authenticated/pengaturan'
import { Route as AuthenticatedPengambilanRouteImport } from './routes/_authenticated/pengambilan'
import { Route as AuthenticatedPembukuanRouteImport } from './routes/_authenticated/pembukuan'
import { Route as AuthenticatedPelangganRouteImport } from './routes/_authenticated/pelanggan'
import { Route as AuthenticatedLanggananRouteImport } from './routes/_authenticated/langganan'
import { Route as AuthenticatedKeuntunganRouteImport } from './routes/_authenticated/keuntungan'
import { Route as AuthenticatedKasirRouteImport } from './routes/_authenticated/kasir'
import { Route as AuthenticatedKaryawanRouteImport } from './routes/_authenticated/karyawan'
import { Route as AuthenticatedKadaluarsaRouteImport } from './routes/_authenticated/kadaluarsa'
import { Route as AuthenticatedHutangRouteImport } from './routes/_authenticated/hutang'
import { Route as AuthenticatedCekKoneksiRouteImport } from './routes/_authenticated/cek-koneksi'
import { Route as AuthenticatedBackupRouteImport } from './routes/_authenticated/backup'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as OauthGoogleSheetsReturnRouteImport } from './routes/oauth.google-sheets.return'
import { Route as ApiPublicMidtransWebhookRouteImport } from './routes/api/public/midtrans-webhook'

const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseSlugRoute = ShowcaseSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShowcaseRoute,
} as any)
const AuthenticatedStokLogRoute = AuthenticatedStokLogRouteImport.update({
  id: '/stok-log',
  path: '/stok-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftRoute = AuthenticatedShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiwayatRoute = AuthenticatedRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromoRoute = AuthenticatedPromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdukRoute = AuthenticatedProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoRoute = AuthenticatedPoRouteImport.update({
  id: '/po',
  path: '/po',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengaturanRoute = AuthenticatedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPengambilanRoute =
  AuthenticatedPengambilanRouteImport.update({
    id: '/pengambilan',
    path: '/pengambilan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPembukuanRoute = AuthenticatedPembukuanRouteImport.update({
  id: '/pembukuan',
  path: '/pembukuan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPelangganRoute = AuthenticatedPelangganRouteImport.update({
  id: '/pelanggan',
  path: '/pelanggan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLanggananRoute = AuthenticatedLanggananRouteImport.update({
  id: '/langganan',
  path: '/langganan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeuntunganRoute = AuthenticatedKeuntunganRouteImport.update({
  id: '/keuntungan',
  path: '/keuntungan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKasirRoute = AuthenticatedKasirRouteImport.update({
  id: '/kasir',
  path: '/kasir',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKaryawanRoute = AuthenticatedKaryawanRouteImport.update({
  id: '/karyawan',
  path: '/karyawan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKadaluarsaRoute = AuthenticatedKadaluarsaRouteImport.update({
  id: '/kadaluarsa',
  path: '/kadaluarsa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHutangRoute = AuthenticatedHutangRouteImport.update({
  id: '/hutang',
  path: '/hutang',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCekKoneksiRoute = AuthenticatedCekKoneksiRouteImport.update({
  id: '/cek-koneksi',
  path: '/cek-koneksi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupRoute = AuthenticatedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OauthGoogleSheetsReturnRoute = OauthGoogleSheetsReturnRouteImport.update({
  id: '/oauth/google-sheets/return',
  path: '/oauth/google-sheets/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMidtransWebhookRoute =
  ApiPublicMidtransWebhookRouteImport.update({
    id: '/api/public/midtrans-webhook',
    path: '/api/public/midtrans-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/cek-koneksi': typeof AuthenticatedCekKoneksiRoute
  '/hutang': typeof AuthenticatedHutangRoute
  '/kadaluarsa': typeof AuthenticatedKadaluarsaRoute
  '/karyawan': typeof AuthenticatedKaryawanRoute
  '/kasir': typeof AuthenticatedKasirRoute
  '/keuntungan': typeof AuthenticatedKeuntunganRoute
  '/langganan': typeof AuthenticatedLanggananRoute
  '/pelanggan': typeof AuthenticatedPelangganRoute
  '/pembukuan': typeof AuthenticatedPembukuanRoute
  '/pengambilan': typeof AuthenticatedPengambilanRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/po': typeof AuthenticatedPoRoute
  '/produk': typeof AuthenticatedProdukRoute
  '/promo': typeof AuthenticatedPromoRoute
  '/riwayat': typeof AuthenticatedRiwayatRoute
  '/shift': typeof AuthenticatedShiftRoute
  '/stok-log': typeof AuthenticatedStokLogRoute
  '/showcase/$slug': typeof ShowcaseSlugRoute
  '/api/public/midtrans-webhook': typeof ApiPublicMidtransWebhookRoute
  '/oauth/google-sheets/return': typeof OauthGoogleSheetsReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/cek-koneksi': typeof AuthenticatedCekKoneksiRoute
  '/hutang': typeof AuthenticatedHutangRoute
  '/kadaluarsa': typeof AuthenticatedKadaluarsaRoute
  '/karyawan': typeof AuthenticatedKaryawanRoute
  '/kasir': typeof AuthenticatedKasirRoute
  '/keuntungan': typeof AuthenticatedKeuntunganRoute
  '/langganan': typeof AuthenticatedLanggananRoute
  '/pelanggan': typeof AuthenticatedPelangganRoute
  '/pembukuan': typeof AuthenticatedPembukuanRoute
  '/pengambilan': typeof AuthenticatedPengambilanRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/po': typeof AuthenticatedPoRoute
  '/produk': typeof AuthenticatedProdukRoute
  '/promo': typeof AuthenticatedPromoRoute
  '/riwayat': typeof AuthenticatedRiwayatRoute
  '/shift': typeof AuthenticatedShiftRoute
  '/stok-log': typeof AuthenticatedStokLogRoute
  '/showcase/$slug': typeof ShowcaseSlugRoute
  '/api/public/midtrans-webhook': typeof ApiPublicMidtransWebhookRoute
  '/oauth/google-sheets/return': typeof OauthGoogleSheetsReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/backup': typeof AuthenticatedBackupRoute
  '/_authenticated/cek-koneksi': typeof AuthenticatedCekKoneksiRoute
  '/_authenticated/hutang': typeof AuthenticatedHutangRoute
  '/_authenticated/kadaluarsa': typeof AuthenticatedKadaluarsaRoute
  '/_authenticated/karyawan': typeof AuthenticatedKaryawanRoute
  '/_authenticated/kasir': typeof AuthenticatedKasirRoute
  '/_authenticated/keuntungan': typeof AuthenticatedKeuntunganRoute
  '/_authenticated/langganan': typeof AuthenticatedLanggananRoute
  '/_authenticated/pelanggan': typeof AuthenticatedPelangganRoute
  '/_authenticated/pembukuan': typeof AuthenticatedPembukuanRoute
  '/_authenticated/pengambilan': typeof AuthenticatedPengambilanRoute
  '/_authenticated/pengaturan': typeof AuthenticatedPengaturanRoute
  '/_authenticated/po': typeof AuthenticatedPoRoute
  '/_authenticated/produk': typeof AuthenticatedProdukRoute
  '/_authenticated/promo': typeof AuthenticatedPromoRoute
  '/_authenticated/riwayat': typeof AuthenticatedRiwayatRoute
  '/_authenticated/shift': typeof AuthenticatedShiftRoute
  '/_authenticated/stok-log': typeof AuthenticatedStokLogRoute
  '/showcase/$slug': typeof ShowcaseSlugRoute
  '/api/public/midtrans-webhook': typeof ApiPublicMidtransWebhookRoute
  '/oauth/google-sheets/return': typeof OauthGoogleSheetsReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/showcase'
    | '/admin'
    | '/backup'
    | '/cek-koneksi'
    | '/hutang'
    | '/kadaluarsa'
    | '/karyawan'
    | '/kasir'
    | '/keuntungan'
    | '/langganan'
    | '/pelanggan'
    | '/pembukuan'
    | '/pengambilan'
    | '/pengaturan'
    | '/po'
    | '/produk'
    | '/promo'
    | '/riwayat'
    | '/shift'
    | '/stok-log'
    | '/showcase/$slug'
    | '/api/public/midtrans-webhook'
    | '/oauth/google-sheets/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/showcase'
    | '/admin'
    | '/backup'
    | '/cek-koneksi'
    | '/hutang'
    | '/kadaluarsa'
    | '/karyawan'
    | '/kasir'
    | '/keuntungan'
    | '/langganan'
    | '/pelanggan'
    | '/pembukuan'
    | '/pengambilan'
    | '/pengaturan'
    | '/po'
    | '/produk'
    | '/promo'
    | '/riwayat'
    | '/shift'
    | '/stok-log'
    | '/showcase/$slug'
    | '/api/public/midtrans-webhook'
    | '/oauth/google-sheets/return'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/showcase'
    | '/_authenticated/admin'
    | '/_authenticated/backup'
    | '/_authenticated/cek-koneksi'
    | '/_authenticated/hutang'
    | '/_authenticated/kadaluarsa'
    | '/_authenticated/karyawan'
    | '/_authenticated/kasir'
    | '/_authenticated/keuntungan'
    | '/_authenticated/langganan'
    | '/_authenticated/pelanggan'
    | '/_authenticated/pembukuan'
    | '/_authenticated/pengambilan'
    | '/_authenticated/pengaturan'
    | '/_authenticated/po'
    | '/_authenticated/produk'
    | '/_authenticated/promo'
    | '/_authenticated/riwayat'
    | '/_authenticated/shift'
    | '/_authenticated/stok-log'
    | '/showcase/$slug'
    | '/api/public/midtrans-webhook'
    | '/oauth/google-sheets/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShowcaseRoute: typeof ShowcaseRouteWithChildren
  ApiPublicMidtransWebhookRoute: typeof ApiPublicMidtransWebhookRoute
  OauthGoogleSheetsReturnRoute: typeof OauthGoogleSheetsReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/$slug': {
      id: '/showcase/$slug'
      path: '/$slug'
      fullPath: '/showcase/$slug'
      preLoaderRoute: typeof ShowcaseSlugRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/_authenticated/stok-log': {
      id: '/_authenticated/stok-log'
      path: '/stok-log'
      fullPath: '/stok-log'
      preLoaderRoute: typeof AuthenticatedStokLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shift': {
      id: '/_authenticated/shift'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof AuthenticatedShiftRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/riwayat': {
      id: '/_authenticated/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof AuthenticatedRiwayatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promo': {
      id: '/_authenticated/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof AuthenticatedPromoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produk': {
      id: '/_authenticated/produk'
      path: '/produk'
      fullPath: '/produk'
      preLoaderRoute: typeof AuthenticatedProdukRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/po': {
      id: '/_authenticated/po'
      path: '/po'
      fullPath: '/po'
      preLoaderRoute: typeof AuthenticatedPoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan': {
      id: '/_authenticated/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthenticatedPengaturanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengambilan': {
      id: '/_authenticated/pengambilan'
      path: '/pengambilan'
      fullPath: '/pengambilan'
      preLoaderRoute: typeof AuthenticatedPengambilanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pembukuan': {
      id: '/_authenticated/pembukuan'
      path: '/pembukuan'
      fullPath: '/pembukuan'
      preLoaderRoute: typeof AuthenticatedPembukuanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pelanggan': {
      id: '/_authenticated/pelanggan'
      path: '/pelanggan'
      fullPath: '/pelanggan'
      preLoaderRoute: typeof AuthenticatedPelangganRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/langganan': {
      id: '/_authenticated/langganan'
      path: '/langganan'
      fullPath: '/langganan'
      preLoaderRoute: typeof AuthenticatedLanggananRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keuntungan': {
      id: '/_authenticated/keuntungan'
      path: '/keuntungan'
      fullPath: '/keuntungan'
      preLoaderRoute: typeof AuthenticatedKeuntunganRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kasir': {
      id: '/_authenticated/kasir'
      path: '/kasir'
      fullPath: '/kasir'
      preLoaderRoute: typeof AuthenticatedKasirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karyawan': {
      id: '/_authenticated/karyawan'
      path: '/karyawan'
      fullPath: '/karyawan'
      preLoaderRoute: typeof AuthenticatedKaryawanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kadaluarsa': {
      id: '/_authenticated/kadaluarsa'
      path: '/kadaluarsa'
      fullPath: '/kadaluarsa'
      preLoaderRoute: typeof AuthenticatedKadaluarsaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hutang': {
      id: '/_authenticated/hutang'
      path: '/hutang'
      fullPath: '/hutang'
      preLoaderRoute: typeof AuthenticatedHutangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cek-koneksi': {
      id: '/_authenticated/cek-koneksi'
      path: '/cek-koneksi'
      fullPath: '/cek-koneksi'
      preLoaderRoute: typeof AuthenticatedCekKoneksiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backup': {
      id: '/_authenticated/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthenticatedBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/oauth/google-sheets/return': {
      id: '/oauth/google-sheets/return'
      path: '/oauth/google-sheets/return'
      fullPath: '/oauth/google-sheets/return'
      preLoaderRoute: typeof OauthGoogleSheetsReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/midtrans-webhook': {
      id: '/api/public/midtrans-webhook'
      path: '/api/public/midtrans-webhook'
      fullPath: '/api/public/midtrans-webhook'
      preLoaderRoute: typeof ApiPublicMidtransWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBackupRoute: typeof AuthenticatedBackupRoute
  AuthenticatedCekKoneksiRoute: typeof AuthenticatedCekKoneksiRoute
  AuthenticatedHutangRoute: typeof AuthenticatedHutangRoute
  AuthenticatedKadaluarsaRoute: typeof AuthenticatedKadaluarsaRoute
  AuthenticatedKaryawanRoute: typeof AuthenticatedKaryawanRoute
  AuthenticatedKasirRoute: typeof AuthenticatedKasirRoute
  AuthenticatedKeuntunganRoute: typeof AuthenticatedKeuntunganRoute
  AuthenticatedLanggananRoute: typeof AuthenticatedLanggananRoute
  AuthenticatedPelangganRoute: typeof AuthenticatedPelangganRoute
  AuthenticatedPembukuanRoute: typeof AuthenticatedPembukuanRoute
  AuthenticatedPengambilanRoute: typeof AuthenticatedPengambilanRoute
  AuthenticatedPengaturanRoute: typeof AuthenticatedPengaturanRoute
  AuthenticatedPoRoute: typeof AuthenticatedPoRoute
  AuthenticatedProdukRoute: typeof AuthenticatedProdukRoute
  AuthenticatedPromoRoute: typeof AuthenticatedPromoRoute
  AuthenticatedRiwayatRoute: typeof AuthenticatedRiwayatRoute
  AuthenticatedShiftRoute: typeof AuthenticatedShiftRoute
  AuthenticatedStokLogRoute: typeof AuthenticatedStokLogRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBackupRoute: AuthenticatedBackupRoute,
  AuthenticatedCekKoneksiRoute: AuthenticatedCekKoneksiRoute,
  AuthenticatedHutangRoute: AuthenticatedHutangRoute,
  AuthenticatedKadaluarsaRoute: AuthenticatedKadaluarsaRoute,
  AuthenticatedKaryawanRoute: AuthenticatedKaryawanRoute,
  AuthenticatedKasirRoute: AuthenticatedKasirRoute,
  AuthenticatedKeuntunganRoute: AuthenticatedKeuntunganRoute,
  AuthenticatedLanggananRoute: AuthenticatedLanggananRoute,
  AuthenticatedPelangganRoute: AuthenticatedPelangganRoute,
  AuthenticatedPembukuanRoute: AuthenticatedPembukuanRoute,
  AuthenticatedPengambilanRoute: AuthenticatedPengambilanRoute,
  AuthenticatedPengaturanRoute: AuthenticatedPengaturanRoute,
  AuthenticatedPoRoute: AuthenticatedPoRoute,
  AuthenticatedProdukRoute: AuthenticatedProdukRoute,
  AuthenticatedPromoRoute: AuthenticatedPromoRoute,
  AuthenticatedRiwayatRoute: AuthenticatedRiwayatRoute,
  AuthenticatedShiftRoute: AuthenticatedShiftRoute,
  AuthenticatedStokLogRoute: AuthenticatedStokLogRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ShowcaseRouteChildren {
  ShowcaseSlugRoute: typeof ShowcaseSlugRoute
}

const ShowcaseRouteChildren: ShowcaseRouteChildren = {
  ShowcaseSlugRoute: ShowcaseSlugRoute,
}

const ShowcaseRouteWithChildren = ShowcaseRoute._addFileChildren(
  ShowcaseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShowcaseRoute: ShowcaseRouteWithChildren,
  ApiPublicMidtransWebhookRoute: ApiPublicMidtransWebhookRoute,
  OauthGoogleSheetsReturnRoute: OauthGoogleSheetsReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
